<a href="https://colab.research.google.com/github/Dan-Maass-Bates/Schedule_Coding/blob/main/Schedule_Coding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')
import pandas as pd
import random
import numpy as np
import time
import math

Mounted at /content/drive/


In [ ]:
curr_file = '/content/drive/My Drive/Seminar/April Break Tour Guide Schedule.csv'
df = pd.read_csv(curr_file)
df.head()

Time     Monday    Tuesday  Wednesday   Thursday  Friday
0   9:00 AM       Emma       Liam     Oliver     Oliver   James
1   9:00 AM       Noah     Sophia      James       Liam    Noah
2   9:00 AM        Ava      James  Sebastian  Charlotte  Oliver
3  11:00 AM       Liam  Charlotte       Liam     Amelia  Amelia
4  11:00 AM  Sebastian     Oliver  Charlotte     Sophia  Sophia

In [ ]:
#names = np.array(range(1,6))
names = ['Mia', 'Emma', 'Charlotte', 'Amelia', 'Sophia', 'Ava', 'Liam', 'Noah', 'Oliver', 'James', 'Sebastian']
#'Student 12', 'Student 13', 'Student 14'
#print(len(names))
num_workers = len(names)
num_jobd = 12
num_jobw = num_jobd * 5


day_max = math.ceil(num_jobd / num_workers)
day_w = math.ceil(num_jobw / num_workers)
print(day_max)
print(day_w)
#if count_monday[n] == day_c - 1 and any(i < day_c - 1 for i in count_monday) == True:
count_week = np.zeros(num_workers)
#print(count_week)
count_monday = np.zeros(num_workers)
#print(len(count_monday))
count_tuesday = np.zeros(num_workers)
count_wednesday = np.zeros(num_workers)
count_thursday = np.zeros(num_workers)
count_friday = np.zeros(num_workers)
count_threshold = np.zeros(num_workers)

start = time.time()
monday_workers = []
while len(monday_workers) < num_jobd:
  n = random.randint(0, int(len(names) - 1))
  name = names[n]
  if count_week[n] == day_w or count_monday[n] == day_max:
    continue
  if count_monday[n] == day_max - 1 and any(i < day_max - 1 for i in count_monday) == True:
    continue
  else:
    count_monday[n] += 1
    count_week[n] += 1
    monday_workers.append(name)
    continue

for i in range(len(count_monday)):
  if count_monday[i] == day_max:
    count_threshold[i] += 1
  else:
    continue


print(count_threshold)
print(max(count_threshold))
#print(monday_workers)
print(count_monday)
tuesday_workers = []
while len(tuesday_workers) < num_jobd:
  n = random.randint(0, int(len(names) - 1))
  name = names[n]
  if count_week[n] == day_w or count_tuesday[n] == day_max:
    continue
  if count_tuesday[n] == day_max - 1 and any(i < day_max - 1 for i in count_tuesday) == True:
    continue
  if count_threshold[n] == max(count_threshold) and count_tuesday[n] == day_max - 1 and any(i < max(count_threshold) for i in count_threshold) == True:
    continue
  else:
    count_tuesday[n] += 1
    count_week[n] += 1
    tuesday_workers.append(name)
    continue

for i in range(len(count_tuesday)):
  if count_tuesday[i] == day_max:
    count_threshold[i] += 1
  else:
    continue


print(tuesday_workers)
print(count_tuesday)
wednesday_workers = []
while len(wednesday_workers) < num_jobd:
  n = random.randint(0, int(len(names) - 1))
  name = names[n]
  if count_week[n] == day_w or count_wednesday[n] == day_max:
    continue
  if count_wednesday[n] >= day_max - 1 and any(i < day_max - 1 for i in count_wednesday) == True:
    continue
  if count_threshold[n] == max(count_threshold) and count_wednesday[n] == day_max - 1 and any(i < max(count_threshold) for i in count_threshold) == True:
    continue
  else:
    count_wednesday[n] += 1
    count_week[n] += 1
    wednesday_workers.append(name)
    #print(count_week)
    continue

for i in range(len(count_wednesday)):
  if count_wednesday[i] == day_max:
    count_threshold[i] += 1
  else:
    continue

print(wednesday_workers)
print(count_wednesday)

thursday_workers = []
while len(thursday_workers) < num_jobd:
  n = random.randint(0, int(len(names) - 1))
  name = names[n]
  if count_week[n] == day_w - 1 or count_thursday[n] == day_max:
    continue
  if count_thursday[n] >= day_max - 1 and any(i < day_max - 1 for i in count_thursday) == True:
    continue
  if count_threshold[n] == max(count_threshold) and count_thursday[n] == day_max - 1 and any(i < max(count_threshold) for i in count_threshold) == True:
    continue
  else:
    count_thursday[n] += 1
    count_week[n] += 1
    thursday_workers.append(name)
    #print(count_week)
    continue

for i in range(len(count_thursday)):
  if count_thursday[i] == day_max:
    count_threshold[i] += 1
  else:
    continue

print(thursday_workers)
print(count_thursday)

friday_workers = []
while len(friday_workers) < num_jobd:
  n = random.randint(0, int(len(names) - 1))
  name = names[n]
  if count_week[n] == day_w or count_friday[n] == day_max:
    continue
  if count_friday[n] >= day_max - 1 and any(i < day_max - 1 for i in count_friday) == True:
    continue
  if count_threshold[n] == max(count_threshold) and count_friday[n] == day_max - 1 and any(i < max(count_threshold) for i in count_threshold) == True:
    continue
  else:
    count_friday[n] += 1
    count_week[n] += 1
    friday_workers.append(name)
    #print(count_friday)
    continue

for i in range(len(count_friday)):
  if count_friday[i] == day_max:
    count_threshold[i] += 1
  else:
    continue
'''if count_week[n] >= day_w - day_max and any(i < day_w - day_max for i in count_week) == True:
    continue'''

'''if count_friday[n] == day_max - 1 and any(i < day_max - 1 for i in count_friday) == True:
    continue'''

'''if count_friday[n] == day_c - 1 and len(set(count_friday)) != 1:
    continue'''

''' ([day_c - 1] * num_workers != count_monday).all()'''

'''all(i >= 30 for i in my_list1)'''
print(friday_workers)
print(count_friday)
print(count_week)
end = time.time()

print(end-start)







2
6
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
1.0
[1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1.]
['Charlotte', 'Emma', 'Noah', 'Amelia', 'Mia', 'Sebastian', 'Ava', 'Oliver', 'Liam', 'Sophia', 'James', 'James']
[1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1.]
['Sophia', 'Oliver', 'Sebastian', 'Mia', 'Charlotte', 'Amelia', 'Ava', 'Noah', 'Emma', 'James', 'Liam', 'Oliver']
[1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1.]
['Sophia', 'Amelia', 'Ava', 'Oliver', 'Sebastian', 'Liam', 'James', 'Emma', 'Charlotte', 'Noah', 'Mia', 'Noah']
[1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1.]
['Mia', 'Oliver', 'Sebastian', 'Emma', 'Liam', 'Ava', 'Amelia', 'Charlotte', 'Noah', 'Sophia', 'James', 'Mia']
[2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[6. 5. 5. 5. 5. 6. 5. 6. 6. 6. 5.]
0.016315937042236328


In [ ]:
times = ['9:00 AM', '9:00 AM', '9:00 AM','11:00 AM','11:00 AM','11:00 AM','1:00 PM','1:00 PM','1:00 PM','3:00 PM','3:00 PM','3:00 PM']
d = {'Time' : times, 'Monday': monday_workers, 'Tuesday': tuesday_workers, 'Wednesday': wednesday_workers, 'Thursday': thursday_workers, 'Friday' : friday_workers}
df = pd.DataFrame(data=d)
df.to_csv(curr_file, index=False)
